name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Spring Boot JAR
        working-directory: ./discord-webhook-service
        run: ./gradlew clean build -x test

      - name: List build/libs to verify JAR creation
        run: ls -alh discord-webhook-service/build/libs

      - name: Copy to EC2 via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: |
            discord-webhook-service/docker-compose.yml
            discord-webhook-service/Dockerfile
            discord-webhook-service/build/libs/webhook-service-*.jar
          target: /home/ubuntu/webhook

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/webhook
            docker stop webhook-service || true
            docker rm webhook-service || true
            docker rmi webhook-service || true
            docker build -t webhook-service .
            docker-compose down || true
            docker-compose up -d
